---
title: 
output: html_document
---
 
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
library(kableExtra)
library(DT)
library(downloadthis)
library(ggplot2)
```

In the grouped pipeline, one sample is processed through one GEM well, resulting in one library which is sequenced across multiple flowcells. This workflow is commonly performed to increase sequencing depth. 

```{r, echo = FALSE}
appliation='cellranger-6.1.1-TS count';

DiagrammeR::grViz("
  digraph graph2 {
  
  graph [layout = dot, rankdir = LR]
  
  # node definitions with substituted label text
  node [shape = box, style=rounded, color=brown, fillcolor=azure3, fontsize=25]
  a [label = '@@1']
  b [label = '@@2']
  c [label = '@@3']
  d [label = '@@4']
  e [label = '@@5']
  
  a -> b -> c -> d -> e
  }
  
  [1]: 'bcl2fastq'
  [2]: appliation[1]
  [3]: 'Generation of metadata'
  [4]: 'Combining multiple sequencing runs'
  [5]: 'Secondary analyses'
  ",
  height = 100)
```


